# Page settings
baseurl = "localhost:1313"
title = "Espacual"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Jordi López"
  description = "Web de Espacual"
  email = "Jordi.Lopez@uab.cat"
  # Navigation
  [params.navigation]
    brand = "Espacual"
    home = "Inicio"
    work = "Actividad"
    testimonials = "Conferencias"
    services = "Formación"
    publicaciones = "Publicaciones"
    about = "Acerca de"
    contact = "Contacto"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "La investigación cualitativa: interpertar el mundo social desde diferentes perspectivas"
    subtitle = 'Espacual, la Asociación Española para el Avance de la investigación Cualitativa'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Asóciate"
    description = "Forma parte de la comunidad Espacual."
    url = "#"
    button = "Asóciate"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Comunidad Espacual en FaceBook"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Comunidad Espacual en Twitter"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Actividad"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Workshop Espacual"
      subtitle = "Comparte los resultados de tu investigación cualitativa"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Conferencia Iberacual"
      subtitle = "La conferencia Iberoamericana de investigación cualitativa"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Formación"
      subtitle = "Seminario avanzado de investigación cualitativa"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Publicaciones"
      subtitle = "Colección fundamentos"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Publicaciones"
      subtitle = "Colección perspectivas"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Publicaciones"
      subtitle = "Colección herramientas digitales"

  # Testimonials -conferences- section
  [params.testimonials]
    enable = true
    title = "Conferencias"
    description = "Comparte los resultados de tu investigación."

    [[params.testimonials.item]]
      quote = "&ldquo; Conferencias nacionales.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Conferencias internacinales en Europa.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Conferencias internacionales fura de Europa. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "Formación"
    description = "Seminarios de formación continuada."

    [[params.services.item]]
      title = "SAIC"
      description = "Seminario avanzado de investigación cualitativa"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Otros seminarios en España"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Otros seminarios en Europa"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "Seminarios herramientas digitales"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "Acerca de"
    description = "Las personas que en estos momentos desarrollan Espacual." 

    [[params.about.item]]
      name = "Jordi López"
      position = "Presidente"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Elena Pérez"
      position = "Vicepresidenta"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Mari Carmen"
      position = "Tesorera"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]   
    [[params.about.item]]
      name = "Carmen de la Cuesta"
      position = "Secreataria"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]   

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Contacta con nosotros"
    description = "Envíanos un correo o llama por teléfono."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Universitat Autònoma de Barcelona, <br> Dept. d'Empresa, Edificio B, despacho B1-118"],
        ["icon-phone", "(93) 5812270"],
        ["icon-envelope", "Presidencia@espacual.es"],
        ["icon-globe", '<a href="http://www.uab.cat/" target="_blank">www.uab.cat</a>']
      ]

    name = "Nombre"
    email = "Email"
    phone = "Teléfono"
    message = "Mensaje"
    button = "Enviar mensaje"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#espacual"],
        ["icon-facebook", "#espacual"],
        ["icon-youtube", "#espacual"]
      ]
  #ignore files
  ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
